
file(GLOB SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
target_sources(Gino
  PRIVATE
  ${SOURCE_FILES})

target_include_directories(Gino
  PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/src
  ${CMAKE_CURRENT_SOURCE_DIR}/include)

install(
  DIRECTORY
  ${CMAKE_CURRENT_SOURCE_DIR}/include
  DESTINATION
  ${CMAKE_INSTALL_PREFIX}
  FILES_MATCHING PATTERN "*.hpp")


