#!/bin/bash -e

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
installDir=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

# Fetch the install directory of NOELLE
noelleInstallDir="`noelle-config --prefix`" ;

# NOELLE tools
ENABLERS="-load ${noelleInstallDir}/lib/LoopInvariantCodeMotion.so \
          -load ${noelleInstallDir}/lib/SCEVSimplification.so \
          "

# Run the enablers until a fixed point is reached
echo "GINO: Enablers: Start" ;
cmdToExecute="noelle-fixedpoint $1 $2 \"gino-load\" ${ENABLERS} -load ${installDir}/lib/Enablers.so -enablers ${@:3}"
echo $cmdToExecute ;
eval $cmdToExecute ;
echo "GINO: Enablers: Exit" ;
