#!/bin/bash -e

installDir=$(gino-config --prefix)

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/GinoCore.so -load ${installDir}/lib/GinoTools.so ${@}"
echo $cmdToExecute ;

# Execute
eval $cmdToExecute ;
