#!/bin/bash -e

trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR

installDir=$(gino-config --prefix)

noelle-load -load ${installDir}/lib/GinoCore.so -load ${installDir}/lib/GinoTools.so ${@}
